#!/bin/sh

# replace "`" with "\`"
PLUGIN_SUCCEED_IF=${PLUGIN_SUCCEED_IF//\`/\\\`}
eval echo 'module.exports = '$(echo \"$PLUGIN_SUCCEED_IF\" | sed 's/\\n//g' ) > /node/plugin-succeed-if.js

echo /node/plugin-succeed-if.js
echo $(cat /node/plugin-succeed-if.js)

# replace "`" with "\`"
PLUGIN_URL=${PLUGIN_URL//\`/\\\`}
eval echo 'module.exports = \`'$(echo \"$PLUGIN_URL\")'\`' > /node/plugin-url.js

echo /node/plugin-url.js
echo $(cat /node/plugin-url.js)

# Remove if exists, ignore errors
rm $PLUGIN_OUT || true
# Create directories if not exists, ignore errors
mkdir -p $(dirname $PLUGIN_OUT) || true

node /node/run.js > $PLUGIN_OUT
